/*
 * Hecho por Ricardo Marin
 */
package puntodeventa;

import puntodeventa.TextPrompt;
import java.awt.Font;

/**
 *
 * @author Ricardo Marin
 */
public class AñadirProducto extends javax.swing.JFrame {

    /**
     * Creates new form AñadirProducto
     */
    
    
    public AñadirProducto() {
        initComponents();
        
        TextPrompt placeholder = new TextPrompt("Nombre del Producto",NombreProducto);
        placeholder.changeAlpha(0.75f);
        placeholder.changeStyle(Font.ITALIC);
        
        TextPrompt placeholder2 = new TextPrompt("Precio del Producto",PrecioProducto);
        placeholder2.changeAlpha(0.75f);
        placeholder2.changeStyle(Font.ITALIC);
        
        TextPrompt placeholder3 = new TextPrompt("Descripción del Producto",DescripcionProducto);
        placeholder3.changeAlpha(0.75f);
        placeholder3.changeStyle(Font.ITALIC);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NombreProducto = new javax.swing.JTextField();
        PrecioProducto = new javax.swing.JTextField();
        NombreLB = new javax.swing.JLabel();
        PrecioLB = new javax.swing.JLabel();
        Acceder = new javax.swing.JButton();
        DescripcionLB = new javax.swing.JLabel();
        DescripcionScroll = new javax.swing.JScrollPane();
        DescripcionProducto = new javax.swing.JTextArea();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NombreProducto.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        NombreProducto.setForeground(new java.awt.Color(60, 38, 27));
        NombreProducto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(NombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 210, 20));

        PrecioProducto.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        PrecioProducto.setForeground(new java.awt.Color(60, 38, 27));
        PrecioProducto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(PrecioProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 210, 20));

        NombreLB.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        NombreLB.setForeground(new java.awt.Color(60, 38, 27));
        NombreLB.setText("Nombre:");
        getContentPane().add(NombreLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 70, 20));

        PrecioLB.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        PrecioLB.setForeground(new java.awt.Color(60, 38, 27));
        PrecioLB.setText("Precio:");
        getContentPane().add(PrecioLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 60, 20));

        Acceder.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        Acceder.setForeground(new java.awt.Color(60, 38, 27));
        Acceder.setText("Añadir");
        Acceder.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(60, 38, 27), 2, true));
        getContentPane().add(Acceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, 90, 30));

        DescripcionLB.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        DescripcionLB.setForeground(new java.awt.Color(60, 38, 27));
        DescripcionLB.setText("Descripción:");
        getContentPane().add(DescripcionLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 100, -1));

        DescripcionProducto.setColumns(20);
        DescripcionProducto.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        DescripcionProducto.setForeground(new java.awt.Color(60, 38, 27));
        DescripcionProducto.setRows(5);
        DescripcionScroll.setViewportView(DescripcionProducto);

        getContentPane().add(DescripcionScroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 470, 140));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AñadirProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AñadirProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AñadirProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AñadirProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AñadirProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Acceder;
    private javax.swing.JLabel DescripcionLB;
    private javax.swing.JTextArea DescripcionProducto;
    private javax.swing.JScrollPane DescripcionScroll;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel NombreLB;
    private javax.swing.JTextField NombreProducto;
    private javax.swing.JLabel PrecioLB;
    private javax.swing.JTextField PrecioProducto;
    // End of variables declaration//GEN-END:variables
}
