/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package puntodeventa;

import javax.swing.JOptionPane;

/**
 *
 * @author Ricardo Marin
 */
public class Cobrar extends javax.swing.JFrame {
    String id_orden;
    /**
     * Creates new form Cobrar
     */
    public Cobrar() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CobrarOrden = new javax.swing.JButton();
        Pedidos = new javax.swing.JScrollPane();
        TablaOrden = new javax.swing.JTable();
        Cobrar = new javax.swing.JLabel();
        Minimizar = new javax.swing.JLabel();
        Cerrar = new javax.swing.JLabel();
        Barra = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Total = new javax.swing.JTextArea();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CobrarOrden.setBackground(new java.awt.Color(255, 255, 255));
        CobrarOrden.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        CobrarOrden.setForeground(new java.awt.Color(60, 38, 27));
        CobrarOrden.setText("Cobrar Orden");
        CobrarOrden.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(60, 38, 27), 2, true));
        CobrarOrden.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CobrarOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CobrarOrdenActionPerformed(evt);
            }
        });
        getContentPane().add(CobrarOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 110, -1));

        Pedidos.setBackground(new java.awt.Color(60, 38, 27));
        Pedidos.setForeground(new java.awt.Color(60, 38, 27));
        Pedidos.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N

        TablaOrden.setBackground(new java.awt.Color(60, 38, 27));
        TablaOrden.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        TablaOrden.setForeground(new java.awt.Color(255, 255, 255));
        TablaOrden.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre Pedido", "Pagado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaOrden.setGridColor(new java.awt.Color(60, 38, 27));
        TablaOrden.setSelectionBackground(new java.awt.Color(78, 182, 172));
        TablaOrden.setSelectionForeground(new java.awt.Color(60, 38, 27));
        TablaOrden.getTableHeader().setResizingAllowed(false);
        TablaOrden.getTableHeader().setReorderingAllowed(false);
        Pedidos.setViewportView(TablaOrden);

        getContentPane().add(Pedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 390, 270));

        Cobrar.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        Cobrar.setForeground(new java.awt.Color(60, 38, 27));
        Cobrar.setText("Ordenes");
        getContentPane().add(Cobrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 100, 30));

        Minimizar.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        Minimizar.setForeground(new java.awt.Color(255, 255, 255));
        Minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minimizar.png"))); // NOI18N
        Minimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizarMouseClicked(evt);
            }
        });
        getContentPane().add(Minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, -1, 30));

        Cerrar.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        Cerrar.setForeground(new java.awt.Color(255, 255, 255));
        Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar.png"))); // NOI18N
        Cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerrarMouseClicked(evt);
            }
        });
        getContentPane().add(Cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, -1, 30));

        Barra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barra.jpg"))); // NOI18N
        getContentPane().add(Barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 50));

        Total.setBackground(new java.awt.Color(60, 38, 27));
        Total.setColumns(20);
        Total.setFont(new java.awt.Font("Leelawadee UI", 0, 21)); // NOI18N
        Total.setForeground(new java.awt.Color(255, 204, 204));
        Total.setRows(5);
        jScrollPane1.setViewportView(Total);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 390, 70));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_MinimizarMouseClicked

    private void CerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarMouseClicked
        UI.CobrarOrden.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_CerrarMouseClicked

    private void CobrarOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CobrarOrdenActionPerformed
        if(PuntoDeVenta.cobrarOrden(id_orden)){
            JOptionPane.showMessageDialog(this, "La orden se ha cobrado con éxito");
            UI.TablaPedidos.setModel(PuntoDeVenta.consultarOrdenesHoy());
        }
        else{
            JOptionPane.showMessageDialog(this, "No se ha podido cobrar la orden");
        }
        
    }//GEN-LAST:event_CobrarOrdenActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        UI.CobrarOrden.setEnabled(false);
        TablaOrden.setModel(PuntoDeVenta.getOrdenACobrar(id_orden));
        Total.setText("El total de la orden es:$"+String.valueOf(PuntoDeVenta.getTotal(id_orden)));
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cobrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cobrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cobrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cobrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cobrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Barra;
    private javax.swing.JLabel Cerrar;
    private javax.swing.JLabel Cobrar;
    private javax.swing.JButton CobrarOrden;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Minimizar;
    private javax.swing.JScrollPane Pedidos;
    public static javax.swing.JTable TablaOrden;
    private javax.swing.JTextArea Total;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
