/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package puntodeventa;

import Animacion.Fade;
import java.awt.Font;
import javax.swing.JOptionPane;

/**
 *
 * @author Ricardo Marin
 */
public class Login extends javax.swing.JFrame {
    PuntoDeVenta obj = new PuntoDeVenta();
    Fade transiciones = new Fade();
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        TextPrompt placeholder = new TextPrompt("Usuario",User);
        placeholder.changeAlpha(0.75f);
        placeholder.changeStyle(Font.ITALIC);
        
        TextPrompt placeholder2 = new TextPrompt("Contraseña",Password);
        placeholder2.changeAlpha(0.75f);
        placeholder2.changeStyle(Font.ITALIC);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        User = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();
        Acceder = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Iniciar Sesión");
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        User.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        User.setForeground(new java.awt.Color(60, 38, 27));
        User.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(User, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 210, -1));

        Password.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        Password.setForeground(new java.awt.Color(60, 38, 27));
        Password.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 210, -1));

        Acceder.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        Acceder.setForeground(new java.awt.Color(60, 38, 27));
        Acceder.setText("Acceder");
        Acceder.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(60, 38, 27), 2, true));
        Acceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccederActionPerformed(evt);
            }
        });
        getContentPane().add(Acceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 90, 30));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       Password.setEchoChar('•');
       obj.conectarBase();
    }//GEN-LAST:event_formWindowOpened

    private void AccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccederActionPerformed
       if(User.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "El campo usuario no puede estar vacío");
       }
       
       else if(Password.getPassword().length==0){
           JOptionPane.showMessageDialog(null, "El campo contraseña no puede estar vacio");
       }
       
       else{
           if(obj.iniciarSesion(User.getText(), Password.getText())){
               Fade.JFrameFadeOut(1f, 0f, 0.05f, 20, this, Fade.HIDE);
               UI ui = new UI();
               ui.id_sesion=obj.sesionIniciada(User.getText(), Password.getText());
               Fade.JFrameFadeIn(0f, 1f, 0.02f, 20, ui);
               ui.setVisible(true);
           }
           
           else{
               JOptionPane.showMessageDialog(null, "Usuario o Contraseña Incorrectos");
           }
           
       }
    }//GEN-LAST:event_AccederActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Acceder;
    private javax.swing.JLabel Fondo;
    private javax.swing.JPasswordField Password;
    private javax.swing.JTextField User;
    // End of variables declaration//GEN-END:variables
}
