/*
 * Hecho por Ricardo Marin
 */
package puntodeventa;

import javax.swing.JOptionPane;

/**
 *
 * @author Ricardo Marin
 */
public class Orden extends javax.swing.JFrame {

    /**
     * Creates new form Orden
     */
    public Orden() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AñadirLB = new javax.swing.JLabel();
        NombreLB1 = new javax.swing.JLabel();
        NombreOrden = new javax.swing.JTextField();
        Crear = new javax.swing.JButton();
        Minimizar = new javax.swing.JLabel();
        Cerrar = new javax.swing.JLabel();
        Barra = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Orden");
        setName("Crear Orden"); // NOI18N
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AñadirLB.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        AñadirLB.setForeground(new java.awt.Color(60, 38, 27));
        AñadirLB.setText("Crear Orden");
        getContentPane().add(AñadirLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 150, 30));

        NombreLB1.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        NombreLB1.setForeground(new java.awt.Color(60, 38, 27));
        NombreLB1.setText("Nombre o Mesa:");
        getContentPane().add(NombreLB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 130, 20));

        NombreOrden.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        NombreOrden.setForeground(new java.awt.Color(60, 38, 27));
        NombreOrden.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(NombreOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 240, 20));

        Crear.setBackground(new java.awt.Color(255, 255, 255));
        Crear.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        Crear.setForeground(new java.awt.Color(60, 38, 27));
        Crear.setText("Crear");
        Crear.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(60, 38, 27), 2, true));
        Crear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearActionPerformed(evt);
            }
        });
        getContentPane().add(Crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 90, 30));

        Minimizar.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        Minimizar.setForeground(new java.awt.Color(255, 255, 255));
        Minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minimizar.png"))); // NOI18N
        Minimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizarMouseClicked(evt);
            }
        });
        getContentPane().add(Minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, -1, 30));

        Cerrar.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        Cerrar.setForeground(new java.awt.Color(255, 255, 255));
        Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar.png"))); // NOI18N
        Cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerrarMouseClicked(evt);
            }
        });
        getContentPane().add(Cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, -1, 30));

        Barra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barra.jpg"))); // NOI18N
        getContentPane().add(Barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 50));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearActionPerformed
        if(NombreOrden.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"El nombre no puede estar vacio");
        }
        else{
            if(PuntoDeVenta.crearOrden(NombreOrden.getText())){
                JOptionPane.showMessageDialog(this, "Orden creada con éxito");
                NombreOrden.setText("");
                UI.TablaPedidos.setModel(PuntoDeVenta.consultarOrdenesHoy());
            }
        }
    }//GEN-LAST:event_CrearActionPerformed

    private void MinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_MinimizarMouseClicked

    private void CerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarMouseClicked
        this.dispose();
    }//GEN-LAST:event_CerrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Orden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Orden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Orden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Orden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Orden().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AñadirLB;
    private javax.swing.JLabel Barra;
    private javax.swing.JLabel Cerrar;
    private javax.swing.JButton Crear;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Minimizar;
    private javax.swing.JLabel NombreLB1;
    private javax.swing.JTextField NombreOrden;
    // End of variables declaration//GEN-END:variables
}
