/*
 * Hecho por Ricardo Marin
 */
package puntodeventa;

import puntodeventa.TextPrompt;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.plaf.basic.BasicListUI;
import jdk.nashorn.internal.runtime.JSType;
import static puntodeventa.UI.TablaFilasOrdenes;
import static puntodeventa.UI.TablaPedidos;

/**
 *
 * @author Ricardo Marin
 */
public class Ordenes extends javax.swing.JFrame {
    /**
     * Creates new form AñadirProducto
     */
    
    
    public Ordenes() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuClick = new javax.swing.JPopupMenu();
        ModificarProducto = new javax.swing.JMenuItem();
        BorrarProducto = new javax.swing.JMenuItem();
        AñadirLB = new javax.swing.JLabel();
        Contenido = new javax.swing.JScrollPane();
        TablaContenido = new javax.swing.JTable();
        Ordenes = new javax.swing.JScrollPane();
        TablaOrdenes = new javax.swing.JTable();
        Minimizar = new javax.swing.JLabel();
        Cerrar = new javax.swing.JLabel();
        Barra = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        MenuClick.setBackground(new java.awt.Color(251, 177, 207));
        MenuClick.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        MenuClick.setForeground(new java.awt.Color(60, 38, 27));
        MenuClick.setBorder(null);
        MenuClick.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        ModificarProducto.setBackground(new java.awt.Color(251, 177, 207));
        ModificarProducto.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        ModificarProducto.setForeground(new java.awt.Color(60, 38, 27));
        ModificarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/orden.png"))); // NOI18N
        ModificarProducto.setText("Modificar Producto");
        ModificarProducto.setToolTipText("");
        ModificarProducto.setBorder(null);
        ModificarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarProductoActionPerformed(evt);
            }
        });
        MenuClick.add(ModificarProducto);

        BorrarProducto.setBackground(new java.awt.Color(251, 177, 207));
        BorrarProducto.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        BorrarProducto.setForeground(new java.awt.Color(60, 38, 27));
        BorrarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        BorrarProducto.setText("Borrar Producto");
        BorrarProducto.setBorder(null);
        BorrarProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BorrarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarProductoActionPerformed(evt);
            }
        });
        MenuClick.add(BorrarProducto);

        setName("Añadir Producto"); // NOI18N
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AñadirLB.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        AñadirLB.setForeground(new java.awt.Color(60, 38, 27));
        AñadirLB.setText("Registro de Ordenes");
        getContentPane().add(AñadirLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 290, 30));

        Contenido.setBackground(new java.awt.Color(60, 38, 27));
        Contenido.setForeground(new java.awt.Color(60, 38, 27));
        Contenido.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N

        TablaContenido.setAutoCreateRowSorter(true);
        TablaContenido.setBackground(new java.awt.Color(60, 38, 27));
        TablaContenido.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        TablaContenido.setForeground(new java.awt.Color(255, 255, 255));
        TablaContenido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre del Producto", "Precio", "Descripción"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaContenido.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        TablaContenido.setComponentPopupMenu(MenuClick);
        TablaContenido.setGridColor(new java.awt.Color(60, 38, 27));
        TablaContenido.setSelectionBackground(new java.awt.Color(78, 182, 172));
        TablaContenido.setSelectionForeground(new java.awt.Color(60, 38, 27));
        TablaContenido.getTableHeader().setResizingAllowed(false);
        TablaContenido.getTableHeader().setReorderingAllowed(false);
        Contenido.setViewportView(TablaContenido);

        getContentPane().add(Contenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 820, 190));

        Ordenes.setBackground(new java.awt.Color(60, 38, 27));
        Ordenes.setForeground(new java.awt.Color(60, 38, 27));
        Ordenes.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N

        TablaOrdenes.setAutoCreateRowSorter(true);
        TablaOrdenes.setBackground(new java.awt.Color(60, 38, 27));
        TablaOrdenes.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        TablaOrdenes.setForeground(new java.awt.Color(255, 255, 255));
        TablaOrdenes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre del Producto", "Precio", "Descripción"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaOrdenes.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        TablaOrdenes.setComponentPopupMenu(MenuClick);
        TablaOrdenes.setGridColor(new java.awt.Color(60, 38, 27));
        TablaOrdenes.setSelectionBackground(new java.awt.Color(78, 182, 172));
        TablaOrdenes.setSelectionForeground(new java.awt.Color(60, 38, 27));
        TablaOrdenes.getTableHeader().setResizingAllowed(false);
        TablaOrdenes.getTableHeader().setReorderingAllowed(false);
        TablaOrdenes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaOrdenesMouseClicked(evt);
            }
        });
        Ordenes.setViewportView(TablaOrdenes);

        getContentPane().add(Ordenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 820, 190));

        Minimizar.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        Minimizar.setForeground(new java.awt.Color(255, 255, 255));
        Minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minimizar.png"))); // NOI18N
        Minimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizarMouseClicked(evt);
            }
        });
        getContentPane().add(Minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, -1, 30));

        Cerrar.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        Cerrar.setForeground(new java.awt.Color(255, 255, 255));
        Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar.png"))); // NOI18N
        Cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerrarMouseClicked(evt);
            }
        });
        getContentPane().add(Cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, -1, 30));

        Barra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barra.jpg"))); // NOI18N
        getContentPane().add(Barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 50));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarMouseClicked
        this.dispose();
    }//GEN-LAST:event_CerrarMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        TablaOrdenes.setModel(PuntoDeVenta.consultarOrdenes());
        TablaOrdenes.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }//GEN-LAST:event_formWindowOpened

    private void MinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_MinimizarMouseClicked

    private void ModificarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarProductoActionPerformed

    }//GEN-LAST:event_ModificarProductoActionPerformed

    private void BorrarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarProductoActionPerformed

    }//GEN-LAST:event_BorrarProductoActionPerformed

    private void TablaOrdenesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaOrdenesMouseClicked
        TablaContenido.setModel(PuntoDeVenta.consultarFilasOrden(String.valueOf(TablaOrdenes.getModel().getValueAt(TablaOrdenes.getSelectedRow(),0))));
    }//GEN-LAST:event_TablaOrdenesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ordenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ordenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ordenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ordenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ordenes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AñadirLB;
    private javax.swing.JLabel Barra;
    private javax.swing.JMenuItem BorrarProducto;
    private javax.swing.JLabel Cerrar;
    private javax.swing.JScrollPane Contenido;
    private javax.swing.JLabel Fondo;
    private javax.swing.JPopupMenu MenuClick;
    private javax.swing.JLabel Minimizar;
    private javax.swing.JMenuItem ModificarProducto;
    private javax.swing.JScrollPane Ordenes;
    public static javax.swing.JTable TablaContenido;
    public static javax.swing.JTable TablaOrdenes;
    // End of variables declaration//GEN-END:variables
}
