/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package puntodeventa;

import Animacion.Fade;
import java.awt.Font;
import javax.swing.JOptionPane;

/**
 *
 * @author Ricardo Marin
 */
public class UI extends javax.swing.JFrame {
    int id_sesion;

    /**
     * Creates new form UI
     */
    public UI() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuClickProductos = new javax.swing.JPopupMenu();
        AñadirAOrden = new javax.swing.JMenuItem();
        ProductosLB = new javax.swing.JLabel();
        FilasOrdenes = new javax.swing.JScrollPane();
        TablaFilasOrdenes = new javax.swing.JTable();
        AñadirProducto = new javax.swing.JLabel();
        CancelarOrden = new javax.swing.JLabel();
        OrdenLB = new javax.swing.JLabel();
        NuevaOrden = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        Busqueda = new javax.swing.JLabel();
        BarraDeBusqueda = new javax.swing.JTextField();
        Productos = new javax.swing.JScrollPane();
        TablaProductos = new javax.swing.JTable();
        Pedidos = new javax.swing.JScrollPane();
        TablaPedidos = new javax.swing.JTable();
        OrdenesLB = new javax.swing.JLabel();
        Cerrar = new javax.swing.JLabel();
        Minimizar = new javax.swing.JLabel();
        Barra = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        MenuClickProductos.setBackground(new java.awt.Color(251, 177, 207));
        MenuClickProductos.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        MenuClickProductos.setForeground(new java.awt.Color(60, 38, 27));
        MenuClickProductos.setBorder(null);
        MenuClickProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        AñadirAOrden.setBackground(new java.awt.Color(251, 177, 207));
        AñadirAOrden.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        AñadirAOrden.setForeground(new java.awt.Color(60, 38, 27));
        AñadirAOrden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/orden.png"))); // NOI18N
        AñadirAOrden.setText("Modificar Producto");
        AñadirAOrden.setToolTipText("");
        AñadirAOrden.setBorder(null);
        AñadirAOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñadirAOrdenActionPerformed(evt);
            }
        });
        MenuClickProductos.add(AñadirAOrden);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ProductosLB.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        ProductosLB.setForeground(new java.awt.Color(60, 38, 27));
        ProductosLB.setText("Contenido de Orden");
        getContentPane().add(ProductosLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 240, 30));

        FilasOrdenes.setBackground(new java.awt.Color(60, 38, 27));
        FilasOrdenes.setForeground(new java.awt.Color(60, 38, 27));
        FilasOrdenes.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N

        TablaFilasOrdenes.setAutoCreateRowSorter(true);
        TablaFilasOrdenes.setBackground(new java.awt.Color(60, 38, 27));
        TablaFilasOrdenes.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        TablaFilasOrdenes.setForeground(new java.awt.Color(255, 255, 255));
        TablaFilasOrdenes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre del Producto", "Precio", "Descripción"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaFilasOrdenes.setGridColor(new java.awt.Color(60, 38, 27));
        TablaFilasOrdenes.setSelectionBackground(new java.awt.Color(78, 182, 172));
        TablaFilasOrdenes.setSelectionForeground(new java.awt.Color(60, 38, 27));
        TablaFilasOrdenes.getTableHeader().setResizingAllowed(false);
        TablaFilasOrdenes.getTableHeader().setReorderingAllowed(false);
        FilasOrdenes.setViewportView(TablaFilasOrdenes);
        if (TablaFilasOrdenes.getColumnModel().getColumnCount() > 0) {
            TablaFilasOrdenes.getColumnModel().getColumn(0).setResizable(false);
            TablaFilasOrdenes.getColumnModel().getColumn(1).setResizable(false);
            TablaFilasOrdenes.getColumnModel().getColumn(2).setResizable(false);
        }

        getContentPane().add(FilasOrdenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, 470, 170));

        AñadirProducto.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        AñadirProducto.setForeground(new java.awt.Color(255, 255, 255));
        AñadirProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Agregar.png"))); // NOI18N
        AñadirProducto.setText("Crear Productos");
        AñadirProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AñadirProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AñadirProductoMouseClicked(evt);
            }
        });
        getContentPane().add(AñadirProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 160, -1));

        CancelarOrden.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        CancelarOrden.setForeground(new java.awt.Color(255, 255, 255));
        CancelarOrden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        CancelarOrden.setText("Cancelar Orden");
        CancelarOrden.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(CancelarOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 160, -1));

        OrdenLB.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        OrdenLB.setForeground(new java.awt.Color(60, 38, 27));
        OrdenLB.setText("Añadir Productos");
        getContentPane().add(OrdenLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 210, 30));

        NuevaOrden.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        NuevaOrden.setForeground(new java.awt.Color(255, 255, 255));
        NuevaOrden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/orden.png"))); // NOI18N
        NuevaOrden.setText("Nueva Orden");
        NuevaOrden.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NuevaOrden.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NuevaOrdenMouseClicked(evt);
            }
        });
        getContentPane().add(NuevaOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.jpeg"))); // NOI18N
        getContentPane().add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 50));

        Busqueda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/busqueda.png"))); // NOI18N
        getContentPane().add(Busqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, -1, 40));

        BarraDeBusqueda.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        BarraDeBusqueda.setForeground(new java.awt.Color(60, 38, 27));
        BarraDeBusqueda.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        BarraDeBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BarraDeBusquedaKeyTyped(evt);
            }
        });
        getContentPane().add(BarraDeBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, 210, 20));

        Productos.setBackground(new java.awt.Color(60, 38, 27));
        Productos.setForeground(new java.awt.Color(60, 38, 27));
        Productos.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N

        TablaProductos.setAutoCreateRowSorter(true);
        TablaProductos.setBackground(new java.awt.Color(60, 38, 27));
        TablaProductos.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        TablaProductos.setForeground(new java.awt.Color(255, 255, 255));
        TablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre del Producto", "Precio", "Descripción"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaProductos.setGridColor(new java.awt.Color(60, 38, 27));
        TablaProductos.setSelectionBackground(new java.awt.Color(78, 182, 172));
        TablaProductos.setSelectionForeground(new java.awt.Color(60, 38, 27));
        TablaProductos.getTableHeader().setResizingAllowed(false);
        TablaProductos.getTableHeader().setReorderingAllowed(false);
        Productos.setViewportView(TablaProductos);
        if (TablaProductos.getColumnModel().getColumnCount() > 0) {
            TablaProductos.getColumnModel().getColumn(0).setResizable(false);
            TablaProductos.getColumnModel().getColumn(1).setResizable(false);
            TablaProductos.getColumnModel().getColumn(2).setResizable(false);
        }

        getContentPane().add(Productos, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 470, 160));

        Pedidos.setBackground(new java.awt.Color(60, 38, 27));
        Pedidos.setForeground(new java.awt.Color(60, 38, 27));
        Pedidos.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N

        TablaPedidos.setBackground(new java.awt.Color(60, 38, 27));
        TablaPedidos.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        TablaPedidos.setForeground(new java.awt.Color(255, 255, 255));
        TablaPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre Pedido", "Pagado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaPedidos.setGridColor(new java.awt.Color(60, 38, 27));
        TablaPedidos.setSelectionBackground(new java.awt.Color(78, 182, 172));
        TablaPedidos.setSelectionForeground(new java.awt.Color(60, 38, 27));
        TablaPedidos.getTableHeader().setResizingAllowed(false);
        TablaPedidos.getTableHeader().setReorderingAllowed(false);
        Pedidos.setViewportView(TablaPedidos);
        if (TablaPedidos.getColumnModel().getColumnCount() > 0) {
            TablaPedidos.getColumnModel().getColumn(0).setResizable(false);
            TablaPedidos.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(Pedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 350, 380));

        OrdenesLB.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        OrdenesLB.setForeground(new java.awt.Color(60, 38, 27));
        OrdenesLB.setText("Ordenes");
        getContentPane().add(OrdenesLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 100, 30));

        Cerrar.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        Cerrar.setForeground(new java.awt.Color(255, 255, 255));
        Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar.png"))); // NOI18N
        Cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerrarMouseClicked(evt);
            }
        });
        getContentPane().add(Cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, -1, 30));

        Minimizar.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        Minimizar.setForeground(new java.awt.Color(255, 255, 255));
        Minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minimizar.png"))); // NOI18N
        Minimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizarMouseClicked(evt);
            }
        });
        getContentPane().add(Minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, -1, 30));

        Barra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barra.jpg"))); // NOI18N
        getContentPane().add(Barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 50));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AñadirProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AñadirProductoMouseClicked
        Productos añadir = new Productos();
        Fade.JFrameFadeIn(0f, 1f, 0.1f, 20, añadir);
        añadir.setVisible(true);
    }//GEN-LAST:event_AñadirProductoMouseClicked

    private void CerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CerrarMouseClicked

    private void MinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_MinimizarMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        TablaProductos.setModel(PuntoDeVenta.consultarProductos());
        TablaPedidos.setModel(PuntoDeVenta.consultarOrdenes());
    }//GEN-LAST:event_formWindowOpened

    private void BarraDeBusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BarraDeBusquedaKeyTyped
        TablaProductos.setModel(PuntoDeVenta.buscarProductos(BarraDeBusqueda.getText()));
    }//GEN-LAST:event_BarraDeBusquedaKeyTyped

    private void NuevaOrdenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NuevaOrdenMouseClicked
        Orden orden = new Orden();
        Fade.JFrameFadeIn(0f, 1f, 0.1f, 20, orden);
        orden.setVisible(true);
    }//GEN-LAST:event_NuevaOrdenMouseClicked

    private void AñadirAOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadirAOrdenActionPerformed
        if(TablaProductos.getSelectedRow()== -1){
            JOptionPane.showMessageDialog(null, "Seleccione una fila despues haga click derecho para modificar");
        }
        else{
            
        } 
            
    }//GEN-LAST:event_AñadirAOrdenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AñadirAOrden;
    private javax.swing.JLabel AñadirProducto;
    private javax.swing.JLabel Barra;
    private javax.swing.JTextField BarraDeBusqueda;
    private javax.swing.JLabel Busqueda;
    private javax.swing.JLabel CancelarOrden;
    private javax.swing.JLabel Cerrar;
    private javax.swing.JScrollPane FilasOrdenes;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Logo;
    private javax.swing.JPopupMenu MenuClickProductos;
    private javax.swing.JLabel Minimizar;
    private javax.swing.JLabel NuevaOrden;
    private javax.swing.JLabel OrdenLB;
    private javax.swing.JLabel OrdenesLB;
    private javax.swing.JScrollPane Pedidos;
    private javax.swing.JScrollPane Productos;
    private javax.swing.JLabel ProductosLB;
    public static javax.swing.JTable TablaFilasOrdenes;
    private javax.swing.JTable TablaPedidos;
    public static javax.swing.JTable TablaProductos;
    // End of variables declaration//GEN-END:variables
}
