/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package puntodeventa;

/**
 *
 * @author Ricardo Marin
 */
public class UI extends javax.swing.JFrame {

    /**
     * Creates new form UI
     */
    public UI() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AñadirProducto = new javax.swing.JLabel();
        CancelarOrden = new javax.swing.JLabel();
        NuevaOrden = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        Busqueda = new javax.swing.JLabel();
        BarraDeBusqueda = new javax.swing.JTextField();
        Productos = new javax.swing.JScrollPane();
        TablaProductos = new javax.swing.JTable();
        Pedidos = new javax.swing.JScrollPane();
        TablaPedidos = new javax.swing.JTable();
        Barra = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AñadirProducto.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        AñadirProducto.setForeground(new java.awt.Color(255, 255, 255));
        AñadirProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Agregar.png"))); // NOI18N
        AñadirProducto.setText("Productos");
        getContentPane().add(AñadirProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 120, -1));

        CancelarOrden.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        CancelarOrden.setForeground(new java.awt.Color(255, 255, 255));
        CancelarOrden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        CancelarOrden.setText("Cancelar Orden");
        getContentPane().add(CancelarOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 160, -1));

        NuevaOrden.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        NuevaOrden.setForeground(new java.awt.Color(255, 255, 255));
        NuevaOrden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/orden.png"))); // NOI18N
        NuevaOrden.setText("Nueva Orden");
        getContentPane().add(NuevaOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, -1, -1));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.jpeg"))); // NOI18N
        getContentPane().add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 50));

        Busqueda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/busqueda.png"))); // NOI18N
        getContentPane().add(Busqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, -1, 40));

        BarraDeBusqueda.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        BarraDeBusqueda.setForeground(new java.awt.Color(60, 38, 27));
        BarraDeBusqueda.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(BarraDeBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, 210, 20));

        Productos.setBackground(new java.awt.Color(60, 38, 27));
        Productos.setForeground(new java.awt.Color(60, 38, 27));
        Productos.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N

        TablaProductos.setBackground(new java.awt.Color(60, 38, 27));
        TablaProductos.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        TablaProductos.setForeground(new java.awt.Color(255, 255, 255));
        TablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Producto", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaProductos.setGridColor(new java.awt.Color(60, 38, 27));
        TablaProductos.setSelectionBackground(new java.awt.Color(78, 182, 172));
        TablaProductos.setSelectionForeground(new java.awt.Color(60, 38, 27));
        TablaProductos.getTableHeader().setResizingAllowed(false);
        TablaProductos.getTableHeader().setReorderingAllowed(false);
        Productos.setViewportView(TablaProductos);
        if (TablaProductos.getColumnModel().getColumnCount() > 0) {
            TablaProductos.getColumnModel().getColumn(0).setResizable(false);
            TablaProductos.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(Productos, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 610, 190));

        Pedidos.setBackground(new java.awt.Color(60, 38, 27));
        Pedidos.setForeground(new java.awt.Color(60, 38, 27));
        Pedidos.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N

        TablaPedidos.setBackground(new java.awt.Color(60, 38, 27));
        TablaPedidos.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        TablaPedidos.setForeground(new java.awt.Color(255, 255, 255));
        TablaPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Pedidos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaPedidos.setGridColor(new java.awt.Color(60, 38, 27));
        TablaPedidos.setSelectionBackground(new java.awt.Color(78, 182, 172));
        TablaPedidos.setSelectionForeground(new java.awt.Color(60, 38, 27));
        TablaPedidos.getTableHeader().setResizingAllowed(false);
        TablaPedidos.getTableHeader().setReorderingAllowed(false);
        Pedidos.setViewportView(TablaPedidos);
        if (TablaPedidos.getColumnModel().getColumnCount() > 0) {
            TablaPedidos.getColumnModel().getColumn(0).setResizable(false);
        }

        getContentPane().add(Pedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 210, 380));

        Barra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barra.jpg"))); // NOI18N
        getContentPane().add(Barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 50));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AñadirProducto;
    private javax.swing.JLabel Barra;
    private javax.swing.JTextField BarraDeBusqueda;
    private javax.swing.JLabel Busqueda;
    private javax.swing.JLabel CancelarOrden;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel NuevaOrden;
    private javax.swing.JScrollPane Pedidos;
    private javax.swing.JScrollPane Productos;
    private javax.swing.JTable TablaPedidos;
    private javax.swing.JTable TablaProductos;
    // End of variables declaration//GEN-END:variables
}
